
DRIVER_LOG = "driver"
BROWSER_LOG = "browser"
LOGS_LEVEL = "ALL"
LOGS_SETUP = {DRIVER_LOG: LOGS_LEVEL, BROWSER_LOG: LOGS_LEVEL}

BROWSER_WIDTH = 1280
BROWSER_HEIGHT = 1024

URL = "http://127.0.0.1:5000/"
